### ISSUE TITLE
Summary - Exceeds Expectations

### ISSUE THREAD

**Issue by tbergen1** [JoshLeT/teacozy2#4]
Overall, you did a fantastic job with this project.  Your formatting and use of comments in both the HTML/CSS made it extremely easy to read and understand your code.  You also demonstrated knowledge of both disciplines by utilizing elements based on their semantics for displaying content and leveraging inheritance for styling in your HTML and CSS, respectively.  Your visuals matched the spec and looked really nice.  Awesome job!  Keep up the great work!

**Comment by JoshLeT** [comment]
Thank you for the kind words!
